### ISSUE TITLE
A question about the area coverage in th paper VR-Caps.

### ISSUE THREAD

**Issue by wu246147** [CapsuleEndoscope/EndoSLAM#10]
In the paper,there is a area coverage algorithm,but it's not a clear description . I want to konw that when you test the Deep Reinforcement Learning (DRL) algorithm , how can you get the number of vertices seen by the capsule camera ? And how did you know how much vertices the stomach total have?

**Comment by DeepMIALab** [comment]
Please submit the issue in the reporistory related with the VR-Caps paper.
