### ISSUE TITLE
Full dataset access

### ISSUE THREAD

**Issue by chunter18** [CapsuleEndoscope/EndoSLAM#11]
Hi, all in a few weeks all dataset will be released as open source. Thank you for your interest.

_Originally posted by @CapsuleEndoscope in https://github.com/CapsuleEndoscope/EndoSLAM/issues/7#issuecomment-808935170_

Hi team, following up on this comment. Has there been any progress on releasing the pill cam data?

**Comment by C-H-Chien** [comment]
Hi, I an also curious about the full available dataset. When will you release it?

**Comment by erezposner** [comment]
Hi, I was wondering if you could provide the camera's calibration params. 

Although the entire dataset is not available yet, one could advance on the sample set that is available in Dropbox. 

Thanks

**Comment by wu246147** [comment]
> Hi, I was wondering if you could provide the camera's calibration params.
> 
> Although the entire dataset is not available yet, one could advance on the sample set that is available in Dropbox.
> 
> Thanks

I wonder if you meam that the entire dataset will not be released later.

**Comment by erezposner** [comment]
@wu246147 What?
I don't know when&if the entire dataset will be released.

**Comment by chunter18** [comment]
Looks like the whole dataset got posted. Link is in the README, but ill share it here as well: https://data.mendeley.com/datasets/cd2rtzm23r/1
