### ISSUE TITLE
test question

### ISSUE THREAD

**Issue by MEcoder27** [CapsuleEndoscope/EndoSLAM#12]

**Comment by MEcoder27** [comment]
How to solve this problem
Traceback (most recent call last):
  File "test_disp.py", line 95, in <module>
    main()
  File "F:\ANACONDA\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test_disp.py", line 87, in main
    np.save(output_dir/"predictions.npy", predictions)
UnboundLocalError: local variable 'predictions' referenced before assignment

**Comment by 201814476285951** [comment]
@zmyl18641515513 
How did you solve this problem please?

**Comment by jinwoo777** [comment]
> [@zmyl18641515513](https://github.com/zmyl18641515513) How did you solve this problem please?

you can simply solve it by converting jpg file to png file
