### ISSUE TITLE
Dataset Resolution doesn't match the paper

### ISSUE THREAD

**Issue by Rashfu** [CapsuleEndoscope/EndoSLAM#14]
The image resolution in `HighCam` folder is `640x480`, which is not consistent with the resolution `1280x720` in paper. 
Anything wrong here?
Thanks for your work.

**Comment by 2017DEVIL** [comment]
Is your problem solved?I have the same problem

**Comment by Rashfu** [comment]
Nope, I don't use this dataset now.

**Comment by 2017DEVIL** [comment]
> Nope, I don't use this dataset now.

Have you found a similar data set? Can you share it? thanks

**Comment by Rashfu** [comment]
You can google MICCAI 2019 Endovis dataset.
