### ISSUE TITLE
UnityCam - normalization and unit measurements of depth map

### ISSUE THREAD

**Issue by jaruanob** [CapsuleEndoscope/EndoSLAM#15]
Hi, first I want to give thanks for the complete and novel synthetic dataset.

But, I'm writing to you to request more details about the normalization, unit measurements, and range of the depth ground truths, specifically of the UnityCAM images. I read the articles related to the database, but I didn't notice such information.

How should I interpret the relationship between the gray level values and the depth? Does each level correspond to 1 millimeter (I guess it is this option), 1 centimeter?

Or these depth maps have been normalized to some minimum and maximum depth values?

Thank you for your time, and I will be pending for your answer.

**Comment by Kutsev-Ozyoruk** [comment]
Hi, 

Could you please submit the question in this repository:
https://github.com/CapsuleEndoscope/VirtualCapsuleEndoscopy

Thank you.
