### ISSUE TITLE
Run depth estimation

### ISSUE THREAD

**Issue by jamesmartin-46** [CapsuleEndoscope/EndoSLAM#5]
Heya, Please may you explain how to run the Endo-SfMLearner to extract depth information from an endoscopic image... I'm a bit confused on what information the shell scripts need. specifically what is gt_depth for eval_depth.py
Thanks

**Comment by CapsuleEndoscope** [comment]
Dear James,
First of all, thank you for your interest to our depth estimation algorithm. We have added "endoSfm_depth_tests.ipynb" to the EnsoSfMLearner folder. I hope that would be helpful. For further question, you may directly contact with Kutsev Bengisu Ozyoruk via bengisu.ozyoruk@boun.edu.tr. 
Take care and stay safe.
