### ISSUE TITLE
endoSfm_depth_tests.ipynb

### ISSUE THREAD

**Issue by meetyogeshhere** [CapsuleEndoscope/EndoSLAM#6]
Hello! Hi 
I am trying to run endoSfm_depth_tests.ipynb notebook.
But when it runs the output of prediction image is very small compare to input and ground truth image.
<img width="1172" alt="Screen Shot 2020-12-17 at 3 46 45 PM" src="https://user-images.githubusercontent.com/25536215/102475330-bc5a7080-407f-11eb-93e2-f84240d430e5.png">

**Comment by CapsuleEndoscope** [comment]
Hi, 

While running the tests you can specify the output dimensions.

Best Regards,
