### ISSUE TITLE
Hi! How can I get the total dataset? 

### ISSUE THREAD

**Issue by ShuweiShao** [CapsuleEndoscope/EndoSLAM#7]

**Comment by chunter18** [comment]
Hey team, just want to second this - the official paper alludes to the whole dataset being available for download. Has any progress been made on releasing it?

Also, want to thank you immensely for this contribution, it really is amazing work.

**Comment by zkaddour** [comment]
I'm also very interested in this dataset for academic work, has any progress been made in releasing it?

**Comment by CapsuleEndoscope** [comment]
Hi, all in a few weeks all dataset will be released as open source. Thank you for your interest.

**Comment by MEcoder27** [comment]
Hello DeepMIA Lab, may I ask how long dataset will be released as open source ? It has been more than two months since your last reply. Your dataset will be very helpful for my research.
