### ISSUE TITLE
Issues of camera calibration files and image datasets of Pillcam

### ISSUE THREAD

**Issue by C-H-Chien** [CapsuleEndoscope/EndoSLAM#8]
Hi,

There are two issues I am concerned about:

(1) According to the README file under the folder `EndoSfMLearner`, there should be a `cam.txt` containing the camera calibration parameters. I know that I can get the parameters from the folder `Calibration`, but I have no idea what the format in `cam.txt` is. Also, only calibrations of `MiroCam` and `PillCam` are provided. Where are the calibration parameters of `LowCam` and `HighCam`?

(2) Downloaded from the [dropbox link](https://www.dropbox.com/s/79q6sitk9w1hepz/EndoSLAM.zip?dl=0&file_subpath=%2FEndoSLAM), only images of `HighCam`, `LowCam`, and `MiroCam` are provided under the folder `Cameras`. Where can I find images of `PillCam`?

Am I correct that, given the limited data, I can only reproduce the experiments of `MiroCam` if I get its format of 'cam.txt' correclty?

**Comment by CapsuleEndoscope** [comment]
Hi,

All required parameters are released in Table Appendix C.2:  
https://arxiv.org/abs/2006.16670
We will release the whole dataset in a few weeks. 

Best Regards,
DeepMIA Lab

**Comment by C-H-Chien** [comment]
How about the format of `cam.txt`? Is there an example for that?
