### ISSUE TITLE
How to run Endo-SfMLearner in Unity environment

### ISSUE THREAD

**Issue by A6248384** [CapsuleEndoscope/EndoSLAM#9]
Hello, Thanks for this project.
I want to run Pose Estimation in Unity .But I hane no idea. Can you tell me how to run on Unity.
Thanks.

**Comment by CapsuleEndoscope** [comment]
Hi, we do not run pose estimation in Unity. We collect the data from VR-Caps environment in Unity and test for pose estimation on this dataset.
